### ISSUE TITLE
Precompiled NIF doesn't pass Integrity check

### ISSUE THREAD

**Issue by ArtieFuzzz** [Vonmo/ex_rock#4]
Tried to compile `ex_rock` in an Elixir project and it failed to pass the integrity check, more info below.

File: `librocker-v0.1.0-nif-2.16-x86_64-unknown-linux-gnu.so.tar.gz`
Expected: e3bc6e14964914b03f26bdf29cf8a7b6894cf5e3f0a15d78d399661458bdeaf5
Got: 1b040d9453526cd89e966576b75ba925a88980b96023a56b3f6042828247fb15

**Comment by Elzor** [comment]
Fixed in v0.1.1
I've created https://github.com/Vonmo/ex_rock_test for autovalidate NIF loading, and added status in readme.md
